In [1]:
!pip install numpy



[notice] A new release of pip is available: 24.0 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [3]:
import numpy as np

In [4]:
a=np.array([1,3,5,7,9])
b = np.array([[1, 2, 3], [4, 5, 6]])


In [6]:
n=np.array([1,2,3])
m=np.array([4,5,6])
s=n+m
print(s)
p=np.sqrt(n)
print(p)

[5 7 9]
[1.         1.41421356 1.73205081]


In [7]:
np.ones((2, 4))
np.eye(3)
np.arange(0, 10, 2)
np.linspace(0, 1, 5)
np.random.rand(3, 2)
np.random.randn(3, 2)
np.zeros((3, 3))


array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [8]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.dtype)


(2, 3)
2
6
int32


In [9]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
a + b
a * b
np.sin(a)


array([0.84147098, 0.90929743, 0.14112001])

In [10]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
np.dot(A, B)
A @ B


array([[19, 22],
       [43, 50]])

In [15]:
arr = np.array([1, 2, 3, 4])
a=arr.sum()
b=arr.mean()
c=arr.max()
d=arr.min()
e=arr.std()
print(a,b,c,d,e)


10 2.5 4 1 1.118033988749895


In [16]:
arr = np.array([1, 2, 3, 4, 5])
print(arr[0])
arr[1:4]
arr[::2]


1


array([1, 3, 5])

In [17]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr[0, 1])
print(arr[:, 1])
print(arr[1, :2])


2
[2 5]
[4 5]


In [18]:
arr = np.array([1, 2, 3, 4, 5])
mask = arr > 3
arr[mask]


array([4, 5])

In [19]:
arr = np.arange(6)
arr.reshape(2, 3)


array([[0, 1, 2],
       [3, 4, 5]])

In [20]:
a = np.array([1, 2])
b = np.array([3, 4])
np.concatenate((a, b))


array([1, 2, 3, 4])

In [21]:
np.vstack((a, b))
np.hstack((a, b))


array([1, 2, 3, 4])

In [22]:
a = np.array([1, 2, 3])
a + 5  

array([6, 7, 8])

In [23]:
np.save('array.npy', arr)

In [24]:
loaded_arr = np.load('array.npy')